api_platform:
    collection:
        pagination:
            enabled: false
    eager_loading:
        max_joins: 200
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
